package com.piiguard.piiguard.web.dto;

import com.piiguard.piiguard.privacy.PiiEntityType;

import java.util.List;
import java.util.Map;

/**
 * The response body for {@code POST /api/proxy}.
 *
 * <p>Note what is <em>not</em> here: the original response echoed {@code originalPrompt} — the
 * user's raw, unredacted text — back in the JSON. Harmless in a single-user demo where the UI
 * wants a before/after diff, and a genuine leak the moment anything logs responses, caches
 * them, or proxies them through a third party. The UI already has the original text; it typed
 * it. It does not need the server to send it back.
 *
 * @param sanitizedPrompt   exactly what was transmitted to the model — the auditable artefact
 * @param llmResponse       the answer, with placeholders restored to real values
 * @param sessionId         correlates this request with its audit row
 * @param attackDetected    whether the request was refused
 * @param detectionMethod   {@code ML}, {@code REGEX}, {@code ML+REGEX} or {@code NONE}
 * @param detectionRule     the specific rule that fired, so a block is explainable
 * @param piiRedacted       counts by type — how many values were protected, never which
 * @param valuesNoised      how many numeric literals were perturbed
 * @param warnings          non-fatal observations, such as sensitive-looking text the model
 *                          generated by itself, surfaced rather than buried in a log
 */
public record ProxyResponse(
        String sanitizedPrompt,
        String llmResponse,
        String sessionId,
        boolean attackDetected,
        String detectionMethod,
        String detectionRule,
        Map<PiiEntityType, Integer> piiRedacted,
        int valuesNoised,
        List<String> warnings) {
}
